function [massuu,stiffnessuu,stiffnessfifi,stiffnessufi,stiffnessfiu] = formStiffnessMass2D(GDofu,GDoffi, ...
    elementNodes,numberNodes,nodeCoordinates,material_type)
%FORMSTIFFNESSMASS2D 主体（无 PML 区）K/M 组装的顶层入口。
%   按 [u | phi] 顺序分块组装 uu / fifi / ufi 三块；fiu 由 ufi 转置得到。
[stiffnessuu,massuu] = formStiffnessMass2Duu(GDofu,GDoffi, ...
    elementNodes,numberNodes,nodeCoordinates,1,'Q9','third',material_type);
stiffnessfifi = formStiffnessMass2Dfi(GDoffi, ...
    elementNodes,numberNodes,nodeCoordinates,1,'Q9','third',material_type);
stiffnessufi = formStiffnessMass2Dufi(GDofu,GDoffi, ...
    elementNodes,numberNodes,nodeCoordinates,1,'Q9','third',material_type);
stiffnessfiu = stiffnessufi';
end
